package seahawksrf.rflanguageproj.com.rhc.entities;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Building Number")
   private java.lang.Integer houseNumber;
   @org.kie.api.definition.type.Label("Street")
   private java.lang.String street;
   @org.kie.api.definition.type.Label("City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label("State")
   private java.lang.String state;
   @org.kie.api.definition.type.Label("Zip Code")
   private java.lang.String zip;

   public Address()
   {
   }

   public java.lang.Integer getHouseNumber()
   {
      return this.houseNumber;
   }

   public void setHouseNumber(java.lang.Integer houseNumber)
   {
      this.houseNumber = houseNumber;
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public Address(java.lang.Integer houseNumber, java.lang.String street,
         java.lang.String city, java.lang.String state, java.lang.String zip)
   {
      this.houseNumber = houseNumber;
      this.street = street;
      this.city = city;
      this.state = state;
      this.zip = zip;
   }

}