package seahawksrf.rflanguageproj.com.rhc.aggregates;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("First Name")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label("Last Name")
   private java.lang.String lastName;

   @org.kie.api.definition.type.Label(value = "Address")
   private seahawksrf.rflanguageproj.com.rhc.entities.Address Address;

   public Customer()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public seahawksrf.rflanguageproj.com.rhc.entities.Address getAddress()
   {
      return this.Address;
   }

   public void setAddress(
         seahawksrf.rflanguageproj.com.rhc.entities.Address Address)
   {
      this.Address = Address;
   }

   public Customer(java.lang.String firstName, java.lang.String lastName,
         seahawksrf.rflanguageproj.com.rhc.entities.Address Address)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.Address = Address;
   }

}